"""#3767 — the reaper's OWNERSHIP CLAIM (containment is not ownership).

`embedded_reaper.py` admitted, as a kill **candidate**, any autogenerated-named
/ tempdir-contained socket dir with no `.db` file. Name and containment are
evidence ANY co-resident redislite application produces, so a server belonging
to another same-uid app, a second tortoise instance, or another tenant sharing
TMPDIR was reachable and reapable — an isolation defect (a more active reaper
scales the kill, which is why #3767 gates #4299).

This module pins the fix in BOTH directions:

  NEGATIVE (acceptance 1/2) — an UNOWNED registry-less dir is `protected`, not
    a candidate, and is not reaped; and an UNATTRIBUTABLE (registry-present but
    no `.tortoise-owners` instrument) no-path server is not fast-killed without
    orphan confirmation.
  POSITIVE (acceptance 3) — our OWN residue is still reaped: an instrumented
    server is still fast-killed, the #1642 FIX 2 dead-pid leftover still
    classifies `stale_socket`, and the #1005 `dir_missing` server is still
    admitted. The reaper is NOT made inert.

The claim itself (`_has_ownership_claim`) is: a PRESENT dir must be owned by
the invoking euid (#4136's property, moved to admission) AND carry tortoise's
own `.tortoise-owners` instrument (#3599); a dir-ABSENT server is admitted by
the live pid's own argv naming it (#1642 FIX 3's pass-1 binding, #4136's
unforgeable arm). The #1557 confirmation window is untouched.

#4546 (OVERRIDES #3767 for the `dir_missing` class ONLY): in a FULL sweep
(`only_safe=False`) `reap()`'s `unattributed` arm exempts a `dir_missing`
record — a LIVE server whose REGISTRY data dir (the pytest `tmp_path` tree) is
already gone, so no on-disk user data remains and pre-#3767 `main` fast-killed
it. (#3767's every-mode `unattributed` requirement CARRIES #1642 FIX 3's "a
missing dir keeps the confirmation window" stance; that carried stance is what
the exemption relaxes, for this class ONLY — #1642 FIX 3's socket-dir-unlinked
window and the `path_based` arm are NOT touched.) The exemption is exactly
that property: `test_dir_missing_unattributed_residue_is_still_fast_killed`
(positive) and `test_unattributed_no_path_server_is_not_fast_killed` (the
dir-PRESENT negative control) are two of its mutation guards, and
`test_path_based_dir_missing_server_is_not_fast_killed` pins the untouched
`path_based` arm. Under `--only-safe` the exemption is unreachable (the
earlier live-pid gate skips first), so `--only-safe` is unchanged.
"""
from __future__ import annotations

import contextlib
import json
import os
import shutil
import socket
import tempfile
from pathlib import Path

import pytest

from tortoise import embedded_reaper as R

pytest.importorskip("redislite")


@pytest.fixture(autouse=True)
def _stand_in_for_live_redis(monkeypatch):
    """A LIVE pgrep'd redis-server is simulated the way the guard READS it
    (#1642 FIX 5's pattern): our own pid is alive, and `_pid_is_redis` says
    it is a redis-server. MIN_UPTIME=0 disables the boot cooldown.
    """
    monkeypatch.setenv("TORTOISE_REAPER_MIN_UPTIME", "0")
    monkeypatch.setattr(R, "_pid_is_redis", lambda pid: pid == os.getpid())
    yield


@contextlib.contextmanager
def _short_base():
    """SHORT ephemeral base — macOS AF_UNIX sun_path is ~104 bytes, so
    pytest's tmp_path is too long for a real socket bind."""
    base = Path(tempfile.mkdtemp(prefix="tt_"))
    try:
        yield base
    finally:
        shutil.rmtree(base, ignore_errors=True)


def _socket_dir(base: Path, name: str) -> Path:
    d = base / name
    d.mkdir()
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.bind(str(d / "redis.socket"))
    s.close()  # a real (dead) socket file persists
    return d


def _instrument(d: Path, pid: int | None = None) -> None:
    """Write tortoise's per-server owner instrument (#3599), as
    `tortoise.FalkorDB`/`record_owner` does in production."""
    od = d / R.OWNERS_DIRNAME
    od.mkdir(exist_ok=True)
    (od / f"{pid if pid is not None else os.getpid()}-1").write_text("")


def _no_path_registry(d: Path, pid: int | None = None) -> None:
    """A redislite registry describing a no-path server rooted in its own
    tempdir (`dbfilename 'redis.db'`) — what a foreign redislite app writes.
    """
    (d / "redis.pid").write_text(f"{pid if pid is not None else os.getpid()}\n")
    (d / "redis.config").write_text(
        f"dbfilename 'redis.db'\ndir '{d}'\npidfile '{d}/redis.pid'\n")


def _no_path_registry_missing_data_dir(d: Path, gone: Path) -> None:
    """Same registry shape, but its `dir` names a path that no longer exists
    — the #4546 residue (`pytest` `tmp_path` teardown removed the data dir
    while the socket dir survived). `dir_missing` is derived from THIS field.
    """
    (d / "redis.pid").write_text(f"{os.getpid()}\n")
    (d / "redis.config").write_text(
        f"dbfilename 'redis.db'\ndir '{gone}'\npidfile '{d}/redis.pid'\n")


# ── #4496: the probes must not raise when `subprocess.run` is mocked ─────────

def test_probless_ps_stdout_is_undeterminable_not_raising(monkeypatch, tmp_path):
    """#4496: a non-text `ps` stdout reads as "undeterminable", never raises.

    Every probe in `embedded_reaper` is documented fail-CLOSED — `None` (or
    an empty result) means "cannot tell" — yet each parses captured
    `ps`/`lsof`/`pgrep` stdout with `.strip()` / `.splitlines()` /
    `re.match`. Dozens of tests fake git detection with
    `mock.patch("subprocess.run")`, whose `stdout` is a MagicMock; the read
    then raised `TypeError` out of a helper whose contract is "or None".

    That was a LEAK, not a crash. The exception propagated through
    `_owner_records` into `cotenant_holds_server`, whose deliberate
    fail-closed `except Exception: return True` then reported a PHANTOM
    co-tenant — so the LAST of two clients on one embedded daemon declined
    the shutdown and the daemon survived uninstrumented with its directory
    present. That is exactly the
    `candidate / path_based=False / unattributed=True / dir_missing=False`
    survivor `test-slow (b)` reports (threshold 0) and #3767 deliberately
    refuses to fast-kill.

    `_owner_records` must also stay total: it is the discriminator the whole
    ownership claim reads, and a raise there is what flipped the close.
    """
    from unittest import mock

    d = tmp_path / "mock-ps"
    owners = d / R.OWNERS_DIRNAME
    owners.mkdir(parents=True)
    # start=1 is a REAL float, which is what makes `_owner_records` consult
    # `ps` at all (an 'unknown' stamp short-circuits to the pid-liveness
    # arm and never reaches the parser — hence the ordering-dependent leak).
    (owners / f"{os.getpid()}-1").write_text("")
    sp = str(d / R.SOCKET_MARKER)

    # Force the single-`ps` fallback: the per-sweep cache would otherwise
    # answer for our own pid. (`delitem`, not an empty record — the cache is
    # fully populated by `_batch_process_info`, so a partial entry is not a
    # shape the probes promise to read.)
    monkeypatch.delitem(R._PROC_INFO_CACHE, os.getpid(), raising=False)

    with mock.patch("subprocess.run") as fake:
        fake.return_value.returncode = 0  # a fake git probe that "succeeds"
        assert R._process_start_time(os.getpid()) is None
        # The owner is still OURS and alive — the undeterminable start must
        # not be read as "no live owner" (that would licence a kill).
        assert R._owner_records(sp) == (1, 1)


def test_uptime_and_cmdline_also_tolerate_a_mock(monkeypatch, tmp_path):
    """The same guard covers the sibling captured-stdout readers.

    `_process_start_time` was the one on the close path (pinned in the test
    above), but the module has eight other readers that parse captured
    `ps`/`lsof`/`pgrep`/`redis-cli` stdout, and only one of the whole set
    raises on a MagicMock (`_parse_lstart`). The rest fail *silently*, which
    is worse — the value they hand back is wrong:

    * `_cmdline` returns the mock itself;
    * `_is_detached` -> `int(MagicMock()) == 1` and `1 in (0, 1)` is **True**,
      i.e. the strongest orphan signal, from an unreadable `ps`;
    * `_client_list`/`_active_client_count` -> `_parse_client_list(MagicMock())`
      is `[]`, the "zero clients" verdict that licences a kill;
    * `_uptime_seconds` -> `_parse_etime(MagicMock())` is `0.0`, the
      *youngest* possible uptime — a wrong value that lands on the SAFE side
      of `_cooldown_check`'s `uptime < min_uptime`. The guard now yields
      `None`, which `_cooldown_check` reads as "not protected by the boot
      cooldown" (the permissive side) — DELIBERATE and pre-existing, not a
      fail-open introduced here: a real `ps` timeout/OSError already produced
      `None` on this path before the guard, and treating a failed probe as
      protected would make the reaper inert whenever `ps` is slow or absent
      (#3599). The safety gates are `reap()`'s owner-record / held-flock /
      orphan-confirmation checks, not this classification — see
      `_cooldown_check`'s comment.

    Deliberately NOT asserted: `_process_has_socket`, `_derive_real_pid_macos`,
    `_pgrep_redis_servers` and `_batch_process_info`. A MagicMock happens to
    yield their safe value already (`"p<pid>" in MagicMock()` is False, and
    iterating `MagicMock().splitlines()` yields nothing), so asserting them
    would pin the contract value while proving nothing about the guard — the
    kind of assertion that reads as coverage and is not.
    """
    from unittest import mock

    monkeypatch.delitem(R._PROC_INFO_CACHE, os.getpid(), raising=False)
    with mock.patch("subprocess.run") as fake:
        fake.return_value.returncode = 0
        assert R._uptime_seconds(os.getpid()) is None  # pre-guard: 0.0
        assert R._cmdline(os.getpid()) == ""  # pre-guard: the mock itself
        assert R._is_detached(os.getpid()) is False  # pre-guard: True
        # `returncode == 0` is redis-cli's own success word, so a non-text
        # stdout must not be parsed as "zero clients" — None is the
        # caller-safe "client state unknown".
        assert R._client_list(str(tmp_path / "nope.sock")) is None
        assert R._active_client_count(str(tmp_path / "nope.sock")) is None


# ── NEGATIVE CONTROL — an unowned dir is NOT ours ────────────────────────────

def test_registryless_unowned_dir_is_not_a_candidate():
    """Acceptance 1 (RED on the unfixed code): an UNOWNED autogenerated-tempdir
    dir with no `.db` file must NOT be admitted as a candidate.

    Pre-fix, `_classify`'s registry-is-None branch fell through to
    `_cooldown_check` on the name/containment heuristic and returned
    'candidate'. Restore `return _cooldown_check(registry, pid=pid)` there and
    this test fails with `assert 'candidate' == 'protected'`.
    """
    with _short_base() as base:
        d = _socket_dir(base, "tmpUNOWNED")  # matches _AUTOGEN_DIRNAME
        # No redis.config / *.settings (registry is None) and NO
        # `.tortoise-owners` instrument: nothing claims this dir as tortoise's.
        assert not (d / R.OWNERS_DIRNAME).exists()
        assert R._classify(str(d / "redis.socket"), os.path.realpath(str(d)),
                           os.path.realpath(str(base)), None,
                           pid=os.getpid()) == "protected"


def test_registryless_unowned_dir_is_not_reaped(monkeypatch):
    """Acceptance 1/2 — the unowned dir is not a candidate and reap() does
    not act on it even in a FULL sweep (`only_safe=False`)."""
    with _short_base() as base:
        d = _socket_dir(base, "tmpUNOWNED")
        rec = R._classify_dir(str(d), str(d / "redis.socket"),
                              known_pid=os.getpid())
        assert rec is not None
        assert rec["classification"] == "protected", rec["classification"]
        assert rec["unattributed"] is True
        killed: list[int] = []
        monkeypatch.setattr(R, "_kill",
                            lambda pid, timeout: killed.append(pid))
        acted = R.reap([dict(rec)], dry_run=False, only_safe=False)
        assert acted == []
        assert killed == [], "an unowned dir must never be reaped"


def test_unattributed_no_path_server_is_not_fast_killed(monkeypatch):
    """Acceptance 1 (the DOMINANT cross-owner route): a foreign no-path
    redislite server with an INTACT registry is admitted as a candidate —
    redislite's registry is written by redislite, not tortoise, so it is not
    an ownership claim — but it has no `.tortoise-owners` instrument, so it
    must NOT be fast-killed without the #1557/#1642 FIX 3 orphan
    confirmation, in EVERY mode. Pre-fix this was killed by any full sweep
    (`path_based=False`, `unattributed` did not exist)."""
    with _short_base() as base:
        d = _socket_dir(base, "tmpFOREIGN")
        _no_path_registry(d)
        rec = R._classify_dir(str(d), str(d / "redis.socket"),
                              known_pid=os.getpid())
        assert rec is not None
        assert rec["classification"] == "candidate"
        assert rec["path_based"] is False  # registry says no-path...
        assert rec["unattributed"] is True  # ...but nothing claims it as OURS
        # #4546 mutation guard: this is the DIR-PRESENT class (#3767's
        # target). Its `dir_missing` is False, so the #4546 exemption must NOT
        # reach it — widening the exemption beyond `dir_missing` REDs here.
        assert rec["dir_missing"] is False
        killed: list[int] = []
        monkeypatch.setattr(R, "_kill",
                            lambda pid, timeout: killed.append(pid))
        monkeypatch.setattr(R, "_active_client_count", lambda _s: 0)
        # Unconfirmed: skipped even in a full sweep (the pre-fix kill path).
        assert R.reap([dict(rec)], dry_run=False, only_safe=False) == []
        assert killed == []
        # Confirmed orphan: still killed — the change is not inertness.
        confirmed = dict(rec, _orphan_confirmed=True)
        R.reap([confirmed], dry_run=False, only_safe=False)
        assert killed == [os.getpid()], killed


def test_is_path_based_fails_closed_without_a_registry():
    """The issue's compounding point: `_is_path_based` used to `return False`
    when the registry was absent, so a registry-less record reported
    `path_based=False` and the strongest protection never engaged. Without a
    registry there is no signal to read, so it must fail CLOSED."""
    with _short_base() as base:
        d = _socket_dir(base, "tmpNOREG")
        assert R._is_path_based(None, os.path.realpath(str(d)),
                                os.path.realpath(str(base))) is True


def test_absent_registryless_dir_needs_the_live_pids_own_argv(monkeypatch):
    """The ownership claim's ABSENT-dir arm (#1005 / #1642 FIX 3 pass-1
    binding), both directions. A registry-less dir that is absent is admitted
    ONLY when the LIVE pid's own argv names it — the one binding a foreign
    uid cannot author (it cannot edit another process's command line). With
    no such binding it is refused. Neither arm was covered before."""
    with _short_base() as base:
        absent = os.path.realpath(str(base / "tmpABSENT"))
        assert not os.path.exists(absent)
        # Bound to the live pid's own argv -> admitted.
        monkeypatch.setattr(R, "_pid_cmdline_names_dir",
                            lambda pid, dbdir: dbdir == absent)
        assert R._has_ownership_claim(absent, os.getpid()) is None
        # No binding -> refused (fail closed).
        monkeypatch.setattr(R, "_pid_cmdline_names_dir",
                            lambda pid, dbdir: False)
        refusal = R._has_ownership_claim(absent, os.getpid())
        assert refusal is not None and "absent" in refusal, refusal


def _load_embedded_orphans():
    """Import tools/embedded_orphans.py by path (it is a CLI, not a module)."""
    import importlib.util
    root = Path(__file__).resolve().parent.parent
    spec = importlib.util.spec_from_file_location(
        "embedded_orphans_3767", root / "tools" / "embedded_orphans.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_census_keeps_socketless_orphans_in_the_orphan_bucket(monkeypatch):
    """#3767 review P1 (regression): a socket-dir-MISSING server is attributed
    by the live pid's OWN argv — the same arm the reaper admits it by — and
    `_owner_record_dir_present` necessarily reads False for it. It must keep
    its `socket-dir-missing` orphan bucket; bucketing it `unattributed` would
    move the whole #1005 socketless leak class out of `orphans` and out of the
    census exit code, i.e. exit 0 while the leak grows."""
    mod = _load_embedded_orphans()
    sock_dir = "/tmp/3767-does-not-exist/tmpX"
    monkeypatch.setattr(mod, "_enumerate_servers_strict", lambda: [os.getpid()])
    # census() imports these from tortoise.embedded_reaper at call time, so
    # they are patched on THAT module, not on the CLI module.
    monkeypatch.setattr(R, "_socket_dir_from_cmdline", lambda pid: sock_dir)
    monkeypatch.setattr(
        R, "_classify_dir",
        lambda d, s, known_pid=None: {"classification": "candidate",
                                      "unattributed": True,
                                      "path_based": False})
    monkeypatch.setattr(R, "_owner_records", lambda s: None)
    monkeypatch.setattr(R, "_socket_dir_missing", lambda s: True)
    res = mod.census()
    assert res["unattributed"] == 0, res
    assert res["orphans"] == 1, res
    assert res["orphan_details"][0]["reason"] == "socket-dir-missing", res


# ── POSITIVE — our own residue is still reaped ──────────────────────────────

def test_tortoise_owned_orphan_is_still_fast_killed(monkeypatch):
    """Acceptance 3: an instrumented (tortoise-owned) no-path server — the
    production shape, since `tortoise.FalkorDB` records `.tortoise-owners` —
    keeps the fast full-sweep kill contract. This is what stops the fix from
    making the reaper inert."""
    with _short_base() as base:
        d = _socket_dir(base, "tmpOWNED")
        _instrument(d)
        _no_path_registry(d)
        rec = R._classify_dir(str(d), str(d / "redis.socket"),
                              known_pid=os.getpid())
        assert rec is not None
        assert rec["classification"] == "candidate"
        assert rec["unattributed"] is False
        killed: list[int] = []
        monkeypatch.setattr(R, "_kill",
                            lambda pid, timeout: killed.append(pid))
        monkeypatch.setattr(R, "_active_client_count", lambda _s: 0)
        R.reap([dict(rec)], dry_run=False, only_safe=False)
        assert killed == [os.getpid()], killed


def test_registryless_claimed_dir_is_admitted(monkeypatch):
    """A registry-less dir that DOES carry the tortoise instrument is ours
    (the #1005 partial-cleanup shape: the redislite config is gone but
    `.tortoise-owners` survives). It is admitted, and — because a missing
    registry cannot prove a disposable no-path server — requires the
    confirmation window like a path-based server."""
    with _short_base() as base:
        d = _socket_dir(base, "tmpCLAIMED")
        _instrument(d)
        rec = R._classify_dir(str(d), str(d / "redis.socket"),
                              known_pid=os.getpid())
        assert rec is not None
        assert rec["classification"] == "candidate"
        assert rec["unattributed"] is False
        killed: list[int] = []
        monkeypatch.setattr(R, "_kill",
                            lambda pid, timeout: killed.append(pid))
        monkeypatch.setattr(R, "_active_client_count", lambda _s: 0)
        # No registry => cannot prove ephemerality => confirmation required.
        assert R.reap([dict(rec)], dry_run=False, only_safe=False) == []
        assert killed == []
        R.reap([dict(rec, _orphan_confirmed=True)], dry_run=False,
               only_safe=False)
        assert killed == [os.getpid()], killed


def test_dead_pid_leftover_still_classifies_stale_socket():
    """Acceptance 3 (#1642 FIX 2): a killed-suite leftover — a dead-pid dir
    with a redislite registry — must still classify `stale_socket` so the
    walk converges on it. The ownership claim applies ONLY to a LIVE server;
    a provably-dead pid has no server to mis-identify."""
    with _short_base() as base:
        d = _socket_dir(base, "tmpLEFT")
        (d / "redis.pid").write_text("99999999\n")  # > pid_max everywhere
        (d / "x.settings").write_text(json.dumps({
            "pidfile": str(d / "redis.pid"),
            "unixsocket": str(d / "redis.socket"),
            "dbdir": str(d),
            "dbfilename": "redis.db",
        }))
        rec = R._classify_dir(str(d), str(d / "redis.socket"))
        assert rec is not None
        assert rec["classification"] == "stale_socket"


def test_registryless_dead_pid_is_still_stale_socket():
    """Acceptance 3, registry-less variant: a provably-DEAD pid is residue
    (the #1642 FIX 2 class) and must route to `stale_socket` even though the
    dir carries no ownership instrument."""
    with _short_base() as base:
        d = _socket_dir(base, "tmpLEF2")
        assert R._classify(str(d / "redis.socket"), os.path.realpath(str(d)),
                           os.path.realpath(str(base)), None,
                           pid=99999999) == "stale_socket"


def test_1005_dir_missing_owned_server_is_still_admitted():
    """Acceptance 3 (#1005): the registry's data dir was cleaned (the pytest
    temp-tree case) but the server's socket dir — and its `.tortoise-owners`
    instrument — survive. The record must still be admitted, with
    `dir_missing=True`."""
    with _short_base() as base:
        d = _socket_dir(base, "tmpOWNED")
        _instrument(d)
        gone = base / "gone-data-dir"
        (d / "x.settings").write_text(json.dumps({
            "dir": str(gone),
            "dbfilename": "redis.db",
            "pidfile": str(d / "redis.pid"),
        }))
        rec = R._classify_dir(str(d), str(d / "redis.socket"),
                              known_pid=os.getpid())
        assert rec is not None
        assert rec["dir_missing"] is True
        assert rec["classification"] == "candidate"
        assert rec["unattributed"] is False


def test_dir_missing_unattributed_residue_is_still_fast_killed(monkeypatch):
    """#4546 (OVERRIDES #3767's every-mode `unattributed` requirement — which
    CARRIES #1642 FIX 3's "a missing dir is not proof of orphanhood → keep the
    window" stance — FOR THE `dir_missing` CLASS ONLY; #1642 FIX 3's
    socket-dir-unlinked window is NOT touched).

    The pytest-residue shape: a LIVE server whose REGISTRY data dir (the
    `tmp_path` tree) was deleted while its SOCKET dir survives, carrying no
    `.tortoise-owners` instrument. It reports `dir_missing=True` +
    `unattributed=True` (`path_based=False`), so before #4546 the branch's
    NEW `unattributed` gate skipped it and it survived a full sweep — the
    `test-slow (b)` orphan-count regression. It must be fast-killed in a FULL
    sweep exactly as pre-#3767 `main` did; no on-disk user data remains once
    the registry data dir is gone.

    RED if the #4546 exemption is removed (the `unattributed` arm skips it).
    This is NOT the socket-dir-absent class: the socket dir is PRESENT here.
    """
    with _short_base() as base:
        d = _socket_dir(base, "tmpRESIDUE")   # socket dir PRESENT
        gone = base / "gone-data"             # the deleted tmp_path data dir
        assert not gone.exists()
        _no_path_registry_missing_data_dir(d, gone)
        rec = R._classify_dir(str(d), str(d / "redis.socket"),
                              known_pid=os.getpid())
        assert rec is not None
        assert rec["classification"] == "candidate"
        assert rec["dir_missing"] is True      # registry data dir gone
        assert rec["unattributed"] is True     # no instrument in socket dir
        assert rec["path_based"] is False
        killed: list[int] = []
        monkeypatch.setattr(R, "_kill",
                            lambda pid, timeout: killed.append(pid))
        monkeypatch.setattr(R, "_active_client_count", lambda _s: 0)
        R.reap([dict(rec)], dry_run=False, only_safe=False)
        assert killed == [os.getpid()], killed


def test_path_based_dir_missing_server_is_not_fast_killed(monkeypatch):
    """#4546 hard constraint: the exemption is scoped to the NEW
    `unattributed` arm. A genuinely PATH-BASED (user-data) server whose
    registry data dir is gone is still gated by the UNTOUCHED `path_based`
    arm — it is not fast-killed in a full sweep, because its data outlives
    the test tree and #1642 FIX 3's confirmation window applies in EVERY mode.

    RED if the exemption is widened to `(path_based and not dir_missing) or
    (unattributed and not dir_missing)` — that mutation lets a `dir_missing`
    user-data server through, which is exactly what the #4546 scoping
    forbids. The socket dir is PRESENT here (registry data dir is the missing
    one).
    """
    with _short_base() as base:
        d = _socket_dir(base, "tmpUSRDATA")   # socket dir PRESENT
        gone = Path("/nonexistent-4546-user-data")  # non-ephemeral user path
        assert not gone.exists()
        (d / "redis.pid").write_text(f"{os.getpid()}\n")
        (d / "redis.config").write_text(
            f"dbfilename 'redis.db'\ndir '{gone}'\npidfile '{d}/redis.pid'\n")
        rec = R._classify_dir(str(d), str(d / "redis.socket"),
                              known_pid=os.getpid())
        assert rec is not None
        assert rec["classification"] == "candidate"
        assert rec["path_based"] is True    # registry 'dir' is a USER path
        assert rec["dir_missing"] is True   # ...and it is gone
        killed: list[int] = []
        monkeypatch.setattr(R, "_kill",
                            lambda pid, timeout: killed.append(pid))
        monkeypatch.setattr(R, "_active_client_count", lambda _s: 0)
        acted = R.reap([dict(rec)], dry_run=False, only_safe=False)
        assert acted == []
        assert killed == [], "a path_based server must keep the gate"


# ── #4577 × #3767: LIVENESS is not ADMISSION ────────────────────────────────

def test_owner_lock_file_alone_is_not_an_ownership_claim(tmp_path):
    """#4577 × #3767 reconciliation: a HELD owner lock is a LIVENESS signal,
    not an admission claim.

    `OWNER_LOCK_NAME` (main `845f47f53`, #4577) lives inside
    `OWNERS_DIRNAME`, so the flock change dropped a new file into the very
    directory #3767's claim reads. If the claim counted it, the lock would
    SILENTLY widen the admission gate — a lock arm would admit a dir whose
    only tortoise marker is a `.lock` a same-uid foreign app can plant and
    flock itself.

    It need not be an admission claim: main's `reap()` already vetoes
    `_owner_lock_held(...) is True` at DESTRUCTION, which is where a liveness
    fact belongs (a dir admitted on a lock arm would be skipped by that very
    check, so the arm could never produce a kill). This test pins the
    separation: a `.tortoise-owners` dir holding only `.lock` carries NO
    claim and `_has_ownership_claim` REFUSES it.

    RED if the lock arm is added to the claim (e.g. `if _owner_lock_held(...)
    is True: return None`) — that is the mutation this pins.
    NOT pinned here: the dotted-name skip in `_owner_record_dir_present`. A
    dotted name could never pass the positive-pid parse anyway
    (`int(".lock".partition("-")[0])` raises ValueError), so the skip is
    intent-documenting rather than load-bearing, and no test can
    mutation-verify it.
    """
    import fcntl

    d = tmp_path / "tmpLOCKONLY"
    d.mkdir()
    od = d / R.OWNERS_DIRNAME
    od.mkdir()
    lock = od / R.OWNER_LOCK_NAME
    lock.write_text("")
    fd = os.open(str(lock), os.O_RDWR)
    try:
        fcntl.flock(fd, fcntl.LOCK_SH)   # a "live owner" holds it
        sock = str(d / "redis.socket")
        assert R._owner_lock_held(sock) is True, (
            "precondition: the held shared lock must read as a live owner")
        assert R._owner_record_dir_present(str(d)) is False, (
            "the `.lock` file alone must not satisfy the ownership claim")
        refusal = R._has_ownership_claim(str(d), os.getpid())
        assert refusal is not None and R.OWNERS_DIRNAME in refusal, refusal
    finally:
        os.close(fd)
