/**
 * /assets/* — a MISSING build asset must not read as a valid one (#3048).
 *
 * THE DEFECT
 * ----------
 * Measured on app.premiselabs.co, 2026-09-11: a request for a hashed chunk that
 * was never deployed answered `200 text/html` with the SPA shell —
 *
 *   GET /assets/index-BKSJiquo.js              -> 200 application/javascript (real)
 *   GET /assets/index-D--Fd1WG.js              -> 200 text/html  4609 bytes  (index.html)
 *   GET /assets/index-DOES-NOT-EXIST-abc123.js -> 200 text/html
 *   GET /assets/nope.css                       -> 200 text/html
 *
 * — so a deleted or rotated chunk looked PRESENT. Deploy verification
 * false-positived on asset existence, missing-asset 404s were invisible to
 * monitoring, and a client holding a stale shell requested a rotated chunk,
 * received `200 text/html`, and died with "Unexpected token '<'" instead of a
 * clean failure.
 *
 * #4006 answered unknown paths on this host with a real `404.html`, which fixed
 * the STATUS — `404` — for every path including this prefix. It did not fix the
 * CONTENT TYPE: `404.html` is an HTML document, so a missing `.js` still came
 * back as `404 text/html`, i.e. an HTML document where JavaScript was asked
 * for. That is the residue this Function removes.
 *
 * WHY A FUNCTION (the mechanism, since it is not obvious and was measured)
 * -----------------------------------------------------------------------
 * `public/_redirects` CANNOT express this. Cloudflare's own docs list
 * "Rewrites (other status codes) ❌ /blog/* /blog/404.html 404" — a `404` status
 * is unsupported — and it is not an error: it is DROPPED SILENTLY. Verified on
 * the real runtime (`npx wrangler@4 pages dev dist`, wrangler 4.127.0): adding
 * `/assets/*  /404.html  404` left wrangler reporting "Parsed 2 valid redirect
 * rules" for a 3-rule file, and the missing asset still answered `404 text/html`.
 * Two further constraints rule the file out anyway:
 *
 *   * "Redirects are always followed, regardless of whether or not an asset
 *     matches the incoming request" — so ANY `/assets/*` rule also rewrites the
 *     REAL bundle, which is why no `_redirects` rule can carry this.
 *   * `_redirects` does not apply to Function responses, and a matching Function
 *     is consulted first on inbound routing (verified in #4104).
 *
 * The project-level `not_found_handling` setting is outside the repo and can
 * only serve `/index.html` (SPA mode, status 200) or `404.html` (status 404) —
 * neither carries a non-HTML body.
 *
 * SCOPE — /assets/* ONLY
 * ----------------------
 * This Function matches the asset prefix and NOTHING else. The app host's
 * not-found contract is deliberate and stays as #4006/#3523 left it: unknown
 * paths are 404 (the app is hash-routed, so the SPA has no deep links to
 * preserve), `/` and `/team` serve the app document at 200, and `/welcome` is
 * owned by `functions/welcome.ts`. A `functions/[[path]].ts` catch-all here
 * would re-widen the very fallback this file narrows.
 *
 * PASS REAL ASSETS THROUGH, FAITHFULLY
 * ------------------------------------
 * A matching Function is consulted BEFORE the static asset router, so `/assets/*`
 * is now this Function's responsibility — including every real request the
 * deployed bundle makes. `env.ASSETS.fetch(request)` re-enters the asset router,
 * and the response is returned VERBATIM, so a real asset keeps the status,
 * `Content-Type`, `Cache-Control` (`public, max-age=0, must-revalidate`), `ETag`
 * (and therefore its `304` on `If-None-Match`), its gzip/Brotli encoding, its
 * `X-Content-Type-Options: nosniff` and its `_headers` policy. Verified on the
 * real runtime by diffing EVERY response header for a real asset served static
 * vs. through this Function: identical apart from `Date`.
 *
 * The pass-through is not decoration — without it this Function would take the
 * entire dashboard bundle down while a "missing asset 404s" assertion stayed
 * green, which is why the regression check asserts the real bundle too.
 *
 * WHY `text/plain` RATHER THAN THE REQUESTED EXTENSION'S TYPE
 * ---------------------------------------------------------
 * The point of the fix is that asset EXISTENCE must be checkable from the
 * response. Answering a missing `.js` with `application/javascript` would leave
 * a content-type-based existence check false-positiving — the exact failure this
 * issue was filed for — so the not-found body is unambiguously NOT any asset
 * type. The status (`404`) is the primary signal; `text/plain` makes the
 * content type agree with it.
 */

// Cloudflare does not apply `_headers` rules to a response generated by a
// Function (only to static assets), so the HSTS policy this origin carries is
// stamped explicitly on the responses built here. Value matches
// `public/_headers` and `tortoise/hosted_api.py` (#1003 §1).
const HSTS = { "Strict-Transport-Security": "max-age=31536000; includeSubDomains" };

export const onRequest: PagesFunction = async ({ request, env }) => {
  // A missing ASSETS binding is a deployment fault, not a 404 — say so (503),
  // never let it read as "the asset you asked for does not exist".
  if (!env.ASSETS) {
    return new Response("Dashboard assets are unavailable.", {
      status: 503,
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "no-store",
        ...HSTS,
      },
    });
  }

  const res = await env.ASSETS.fetch(request);

  // A real asset (or a redirect the asset router emits, e.g. the `.html` →
  // extension-less normalization) — return it untouched, headers and all. Only
  // the not-found case is ours to answer.
  if (res.status !== 404) return res;

  // `no-store`: a cacheable 404 would keep answering for a path that a later
  // deploy may legitimately ship (the hashed names change per build, but a
  // non-hashed asset does not). `nosniff` is belt-and-braces on the explicit
  // `text/plain` — a browser must never reinterpret this body as script.
  return new Response("Not found\n", {
    status: 404,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store",
      "X-Content-Type-Options": "nosniff",
      ...HSTS,
    },
  });
};
