/**
 * GET /auth — the front door.
 *
 * WHY THIS EXISTS (#4054)
 * -----------------------
 * The auth surface used to live in the MARKETING Pages project
 * (`premise-labs`, `tortoise.premiselabs.co`), whose root `_middleware.ts`
 * rewrote `/auth` (and `/auth.html`) to the `/signup` asset. The topology
 * decision moved the session-bearing layer to the APP origin
 * (`app.premiselabs.co`, the `tortoise-dashboard` project) — and the middleware
 * stayed behind, so the app origin had NO `/auth` route: a request for
 * `https://app.premiselabs.co/auth` fell through to the SPA fallback and
 * answered 200 with the React shell. That is a silent, wrong "success".
 *
 * This Function restores the route on the app origin with the SAME semantics the
 * marketing middleware had — rewrite to the extensionless `/signup` asset,
 * PRESERVING the query string. Params MUST survive: the #1224 OAuth
 * state-expiry banner reads `?error=…` from the URL, and invite / recovery
 * links arriving here carry `?token=…` / `?type=recovery`.
 *
 * SCOPED TO /auth ON PURPOSE
 * --------------------------
 * `functions/auth/index.ts` matches EXACTLY `/auth` (and `/auth/`). A
 * project-wide `functions/_middleware.ts` would have wrapped `/api/*`, every
 * other `/auth/*` route (`/auth/start`, `/auth/callback`, `/auth/signup`, …)
 * and the SPA fallback as well. The blast radius of a middleware is the whole
 * project; the blast radius of this file is one path.
 *
 * SERVE, DO NOT REDIRECT
 * ----------------------
 * This returns the asset response rather than 302-ing to `/signup`. A redirect
 * would lose POST semantics and add a hop; `signup.html` is the page the
 * visitor asked for, so serving it at `/auth` is equivalent and cheaper.
 *
 * HSTS (#1003 §1): Cloudflare does NOT apply `_headers` rules to responses
 * generated by Pages Functions — only to static assets — so the header is
 * stamped here. Value matches the API (`tortoise/hosted_api.py`) and the
 * dashboard's `public/_headers`: max-age=31536000; includeSubDomains, no
 * `preload` yet (soak first per #1003 §1).
 */
import { RELAXED_CSP } from "../_shared/security-headers";

const HSTS = "max-age=31536000; includeSubDomains";

export const onRequest: PagesFunction = async ({ request, env }) => {
  // A Function response never falls back to `_headers`, and a missing ASSETS
  // binding is a deployment fault, not a sign-out — 503, never a redirect.
  if (!env.ASSETS) {
    return new Response("Auth page assets unavailable", {
      status: 503,
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Strict-Transport-Security": HSTS,
      },
    });
  }

  const url = new URL(request.url);

  // Clean-URL resolution serves `signup.html` for `/signup` (the same
  // resolution the marketing middleware relied on). The Request (not a bare
  // URL) is passed through so method, headers and body are preserved — exactly
  // as the middleware's `context.next(new Request(...))` did.
  const assetUrl = new URL(url.origin + "/signup" + url.search);
  const res = await env.ASSETS.fetch(new Request(assetUrl, request));

  const headers = new Headers(res.headers);
  headers.set("Strict-Transport-Security", HSTS);
  headers.set("Content-Type", "text/html; charset=utf-8");
  headers.set("Cache-Control", "public, max-age=60");
  headers.set("Content-Security-Policy", RELAXED_CSP);

  return new Response(res.body, { status: res.status, headers });
};
