/**
 * Content-Security-Policy constants — #3525.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * `_headers` is a Cloudflare Pages **static-asset** feature: the platform does
 * not apply it to responses generated by Pages Functions (documented, and
 * confirmed by the sibling comment in `auth/index.ts`). Every Function that
 * produces HTML therefore has to stamp its own `Content-Security-Policy`, so the
 * policy text lives here once instead of being re-typed (and silently drifting)
 * at each site.
 *
 * THREE TRUST LEVELS, NOT ONE
 * ---------------------------
 * The app origin serves three different things, so an origin-wide policy would
 * have to be the weakest of the three:
 *
 *   - `STRICT_CSP`  — the dashboard SPA document. Vite emits only external
 *                     bundles; there is no inline script, no eval, and every
 *                     request is same-origin (`API_BASE = '/api'`). So
 *                     `script-src 'self'` is safe *and* it is the surface where
 *                     the session is USED, which is the whole point of #3525.
 *                     `style-src` keeps `'unsafe-inline'` because React renders
 *                     ~130 inline `style={{…}}` attributes — without it every
 *                     page would render unstyled.
 *   - `ADMIN_CSP`   — the `/admin` console shell. Also no inline script, but it
 *                     talks to Supabase directly (supabase-js data + storage),
 *                     and it PREVIEWS author-supplied image URLs, so `img-src`
 *                     must stay broad (`https:`). Narrowing it to Supabase
 *                     blanks the editor's previews.
 *   - `RELAXED_CSP` — the pre-#3501 pages: the auth pages (`/auth`, `/welcome`,
 *                     `/invite-accept`), the marketing pages and the blog SSR.
 *                     These still carry inline `<script>`, inline `<style>` and
 *                     inline event handlers, which CANNOT be nonced (handlers
 *                     need `'unsafe-hashes'` + a hash each). `'unsafe-inline'`
 *                     is therefore a deliberate, TEMPORARY concession: #3501
 *                     deletes the inline handlers, after which `script-src` here
 *                     is tightened to match `STRICT_CSP`. Even with the
 *                     concession this is a real hardening — `object-src 'none'`,
 *                     `base-uri 'none'`, `frame-ancestors 'none'`,
 *                     `form-action 'self'` all bite, and `script-src` is bounded
 *                     to a known origin set.
 *
 * ORIGINS ARE NOT SPECULATIVE
 * ---------------------------
 * Each origin in `RELAXED_CSP` is the one a loader actually uses (see the
 * #3525 scope/plan doc, `docs/plans/2026-09-22-3525-csp-no-store.md`). Omitting
 * one breaks a live feature silently. GTM (`GTM-WQR34GSC`) can be configured to
 * load NEW tag origins at any time — adding a tag means updating this constant
 * in the same change.
 *
 * The guard `src/securityHeaders.test.js` asserts each constant is byte-identical
 * to its `_headers` counterpart, so the duplication above cannot drift.
 */

/** Join directives with the canonical `; ` separator, no trailing semicolon. */
const csp = (...directives: string[]): string => directives.join("; ");

/**
 * Static-asset default for both Pages projects, and the Function HTML of the
 * pre-#3501 pages. See the file header for why `'unsafe-inline'` is here.
 */
export const RELAXED_CSP = csp(
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://us-assets.i.posthog.com https://www.googletagmanager.com https://connect.facebook.net https://challenges.cloudflare.com",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://*.supabase.co https://api.premiselabs.co https://us.i.posthog.com https://us-assets.i.posthog.com https://www.googletagmanager.com https://www.google-analytics.com https://region1.google-analytics.com https://connect.facebook.net https://www.facebook.com https://challenges.cloudflare.com",
  "frame-src https://challenges.cloudflare.com",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
);

/** The dashboard SPA document (`/`, `/team`, `/team/`, `/index.html`). */
export const STRICT_CSP = csp(
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self'",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
);

/** The `/admin` console shell — `STRICT_CSP` plus the Supabase origins it uses. */
export const ADMIN_CSP = csp(
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://*.supabase.co wss://*.supabase.co",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
);

/**
 * `STRICT_CSP` with a per-response nonce for the `/auth/confirm` interstitial —
 * the one self-rendered HTML page in the dashboard, and the one that can be
 * nonce-gated because it has no inline event handlers. This is the treatment the
 * MCP consent page already uses (`tortoise/hosted_api.py`), and it is stricter:
 * the consent page also allows a CDN, this page needs no external script.
 */
export function strictCspWithNonce(nonce: string): string {
  return csp(
    "default-src 'self'",
    `script-src 'nonce-${nonce}'`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    "connect-src 'self'",
    "object-src 'none'",
    "base-uri 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
  );
}

/** 128 bits of CSPRNG, base64 — the standard nonce shape. */
export function cspNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode(...bytes));
}
