/**
 * Content-Security-Policy constants — #3525.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * `_headers` is a Cloudflare Pages **static-asset** feature: the platform does
 * not apply it to responses generated by Pages Functions (documented, and
 * confirmed by the sibling comment in `auth/index.ts`). Every Function that
 * produces HTML therefore has to stamp its own `Content-Security-Policy`, so the
 * policy text lives here once instead of being re-typed (and silently drifting)
 * at each site.
 *
 * THREE TRUST LEVELS, NOT ONE
 * ---------------------------
 * The app origin serves three different things, so an origin-wide policy would
 * have to be the weakest of the three:
 *
 *   - `STRICT_CSP`  — the dashboard SPA document. Vite emits only external
 *                     bundles; there is no inline script, no eval, and every
 *                     request is same-origin (`API_BASE = '/api'`). So
 *                     `script-src 'self'` is safe *and* it is the surface where
 *                     the session is USED, which is the whole point of #3525.
 *                     `style-src` keeps `'unsafe-inline'` because React renders
 *                     ~130 inline `style={{…}}` attributes — without it every
 *                     page would render unstyled.
 *   - `ADMIN_CSP`   — the `/admin` console shell. Also no inline script, but it
 *                     talks to Supabase directly (supabase-js data + storage),
 *                     and it PREVIEWS author-supplied image URLs, so `img-src`
 *                     must stay broad (`https:`). Narrowing it to Supabase
 *                     blanks the editor's previews.
 *   - `RELAXED_CSP` — the pre-#3501 pages: the auth pages (`/auth`, `/welcome`,
 *                     `/invite-accept`), the marketing pages and the blog SSR.
 *                     These still carry inline `<script>`, inline `<style>` and
 *                     inline event handlers, which CANNOT be nonced (handlers
 *                     need `'unsafe-hashes'` + a hash each). `'unsafe-inline'`
 *                     is therefore a deliberate, TEMPORARY concession: #3501
 *                     deletes the inline handlers, after which `script-src` here
 *                     is tightened to match `STRICT_CSP`. Even with the
 *                     concession this is a real hardening — `object-src 'none'`,
 *                     `base-uri 'none'`, `frame-ancestors 'none'`,
 *                     `form-action 'self'` all bite, and `script-src` is bounded
 *                     to a known origin set.
 *
 * ORIGINS ARE NOT SPECULATIVE
 * ---------------------------
 * Each origin in `RELAXED_CSP` is the one a loader actually uses (see the
 * #3525 scope/plan doc, `docs/plans/2026-09-22-3525-csp-no-store.md`). Omitting
 * one breaks a live feature silently. GTM (`GTM-WQR34GSC`) can be configured to
 * load NEW tag origins at any time — adding a tag means updating this constant
 * in the same change.
 *
 * THE PLATFORM INJECTS A SCRIPT WE DID NOT WRITE
 * ----------------------------------------------
 * Cloudflare Web Analytics is enabled for this zone, so the EDGE injects
 * `https://static.cloudflareinsights.com/beacon.min.js/<version>` into HTML
 * responses. The trigger is the REQUEST's `Accept` header, not the User-Agent: a
 * plain `curl` sends a wildcard `Accept` and gets the un-injected document, while
 * `curl -H 'Accept: text/html' https://premiselabs.co/` shows the tag. That is
 * the cheap pre-merge detector for this whole class — a local
 * `wrangler pages dev` preview never sees it, because the preview is not the
 * edge. The first version of this change shipped a policy that blocked it, and
 * only the post-merge `verify-legal` suite (production, real browser, asserting
 * zero console errors) noticed: 8 failures.
 *
 * What the SRI pin does and does NOT buy. The injected tag is SRI-pinned by the
 * platform (`integrity="sha512-…" crossorigin="anonymous"`) and version-named,
 * so the platform's OWN tag cannot be silently swapped for a modified build. It
 * does NOT constrain this CSP entry: `script-src https://static.cloudflareinsights.com`
 * is an ORIGIN allowance and CSP never consults a hash, so the entry also admits
 * any OTHER script served from that origin — that widening is the residual
 * recorded in the #3525 plan doc. Nor is the pin ours to rely on: it is emitted
 * by the edge, so if Cloudflare's injection format changes, this policy becomes
 * a blanket third-party-script allowance with no repo change and no failing test.
 *
 * The beacon reports to `https://cloudflareinsights.com/cdn-cgi/rum`, hence the
 * `connect-src` entry — which has no hash mechanism at all. Every policy below
 * names both, and `securityHeaders.test.js` fails if one does not, because the
 * failure mode is silent (analytics lost, plus a console error on a live page).
 *
 * The guard `src/securityHeaders.test.js` asserts each constant is byte-identical
 * to its `_headers` counterpart, so the duplication above cannot drift.
 */

/** Join directives with the canonical `; ` separator, no trailing semicolon. */
const csp = (...directives: string[]): string => directives.join("; ");

/**
 * Static-asset default for both Pages projects, and the Function HTML of the
 * pre-#3501 pages. See the file header for why `'unsafe-inline'` is here.
 */
export const RELAXED_CSP = csp(
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com https://cdnjs.cloudflare.com https://us-assets.i.posthog.com https://www.googletagmanager.com https://connect.facebook.net https://challenges.cloudflare.com",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://cloudflareinsights.com https://*.supabase.co https://api.premiselabs.co https://us.i.posthog.com https://us-assets.i.posthog.com https://www.googletagmanager.com https://www.google-analytics.com https://region1.google-analytics.com https://connect.facebook.net https://www.facebook.com https://challenges.cloudflare.com",
  "frame-src https://challenges.cloudflare.com",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
);

/** The dashboard SPA document (`/`, `/team`, `/team/`, `/index.html`). */
export const STRICT_CSP = csp(
  "default-src 'self'",
  "script-src 'self' https://static.cloudflareinsights.com",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self' https://cloudflareinsights.com",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
);

/** The `/admin` console shell — `STRICT_CSP` plus the Supabase origins it uses. */
export const ADMIN_CSP = csp(
  "default-src 'self'",
  "script-src 'self' https://static.cloudflareinsights.com",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://cloudflareinsights.com https://*.supabase.co wss://*.supabase.co",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
);

/**
 * `STRICT_CSP` with a per-response nonce for the `/auth/confirm` interstitial —
 * the one self-rendered HTML page in the dashboard, and the one that can be
 * nonce-gated because it has no inline event handlers. This is the treatment the
 * MCP consent page already uses (`tortoise/hosted_api.py`). It is NOT nonce-only:
 * like the consent page it carries one extra host beside the nonce, and here that
 * host is the platform-injected beacon origin (every policy must carry it — see
 * the header). The page AUTHORS one inline script, and that one still needs the
 * nonce; any script served from the beacon origin would run here un-nonced.
 */
export function strictCspWithNonce(nonce: string): string {
  return csp(
    "default-src 'self'",
    `script-src 'nonce-${nonce}' https://static.cloudflareinsights.com`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    "connect-src 'self' https://cloudflareinsights.com",
    "object-src 'none'",
    "base-uri 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
  );
}

/** 128 bits of CSPRNG, base64 — the standard nonce shape. */
export function cspNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode(...bytes));
}
